//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnZipper {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\t-takemura\\Documents\\Visual Studio 2010\\Projects\\UnZipper\\UnZipper\\bin\\D" +
            "ebug")]
        public string 自動解凍対象監視フォルダ {
            get {
                return ((string)(this["自動解凍対象監視フォルダ"]));
            }
            set {
                this["自動解凍対象監視フォルダ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\t-takemura\\Documents\\Visual Studio 2010\\Projects\\UnZipper\\UnZipper\\bin\\D" +
            "ebug\\UnZipperTemp")]
        public string 作業フォルダ {
            get {
                return ((string)(this["作業フォルダ"]));
            }
            set {
                this["作業フォルダ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int 監視間隔ミリ秒 {
            get {
                return ((int)(this["監視間隔ミリ秒"]));
            }
            set {
                this["監視間隔ミリ秒"] = value;
            }
        }
    }
}
